// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-ZqSQg3opMPagaMvYW4OYpF7XqLJ450',
    appId: '1:904056375301:web:95955b9f23679fd98ff46c',
    messagingSenderId: '904056375301',
    projectId: 'brew-crew-8f4ca',
    authDomain: 'brew-crew-8f4ca.firebaseapp.com',
    storageBucket: 'brew-crew-8f4ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBps-mxGcrRUjwpr1V5wt63_eA1lYeKXhQ',
    appId: '1:904056375301:android:bdce254f8ae802178ff46c',
    messagingSenderId: '904056375301',
    projectId: 'brew-crew-8f4ca',
    storageBucket: 'brew-crew-8f4ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADxKUhvCP4zBfGopUsgMSQ2bsteJ0XMJc',
    appId: '1:904056375301:ios:74c2645dcf24d9088ff46c',
    messagingSenderId: '904056375301',
    projectId: 'brew-crew-8f4ca',
    storageBucket: 'brew-crew-8f4ca.appspot.com',
    iosClientId: '904056375301-h79gclm0vuosa2pblkmeu1002nn8ag6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADxKUhvCP4zBfGopUsgMSQ2bsteJ0XMJc',
    appId: '1:904056375301:ios:74c2645dcf24d9088ff46c',
    messagingSenderId: '904056375301',
    projectId: 'brew-crew-8f4ca',
    storageBucket: 'brew-crew-8f4ca.appspot.com',
    iosClientId: '904056375301-h79gclm0vuosa2pblkmeu1002nn8ag6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
